php-version = "8.5.0"

[source]
workspace = "."
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
preset = "default"
space-after-logical-not-unary-prefix-operator = true
space-before-arrow-function-parameter-list-parenthesis = true
always-break-named-arguments-list = true

[linter]
integrations = ["phpunit", "tempest"]

[linter.rules]
literal-named-argument = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
assertion-style = { style = "$this"}
class-name = { enabled = false}
interface-name = { enabled = false}
trait-name = { enabled = false}
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }
no-else-clause = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
yoda-conditions = { enabled = false }
no-redundant-file = { enabled = false }
no-isset = { enabled = false }

[analyzer]
plugins = []
analyze-dead-code = true
memoize-properties = true
check-missing-override = true
check-missing-type-hints = true
register-super-globals = true
check-use-statements = true